export type Asset = string | { src: string; columns: number; rows: number; index: number };
export type Fact = { icon: string; title: string; description: string };
export type Feature = { title: string; description: string; icon: string };
export type Service = {
  slug: string;
  name: string;
  headline: string[];
  description: string;
  image: string;
  script: string;
  introTitle: string;
  introText: string;
  introImage: string;
  features: Feature[];
  accent: string;
  icon: string;
  introFacts: Fact[];
  heroFacts: Fact[];
  introBadge: string;
  introBadgeLabel: string;
  featureTitle: string;
  processTitle: string;
  processStyle: string;
  processLabels: string[];
  technologies: string[];
  stats: string[][];
  projects: string[];
  projectTitle: string;
  testimonialTitle: string;
  ctaTitle: string;
  ctaText: string;
  ctaLabel: string;
  ctaImage: string;
  ctaScript: string;
  heroBadge?: string;
  heroBadgeLabel?: string;
  heroPanel?: string[];
};
export type Project = {
  slug: string;
  title: string;
  category: string;
  filter: string;
  description: string;
  image: Asset;
  services: string[];
  overview: string;
};
export type Testimonial = {
  name: string;
  role: string;
  quote: string;
  initials: string;
  color: string;
};
